FROM python:3.11-slim

# Instala dependências
RUN apt-get update && apt-get install -y build-essential gcc libpq-dev

# Instala pip e pacotes
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

